### PR TITLE
password and password confimation validation error in right place

### PR DESCRIPTION
**Pull request by aboutaleb-dev**
Hello

Right now in code when we try to register if all of password and password confirmation will show under the password field.
so I thought showing them in their right place is a better Idea so I edited RegisteredUserController.php file.

At the end it is your choice to what you want to use and this is just my suggestion.

### CODE REVIEW

**Comment by GILLESMaster** [comment]
This does actually make sense in my head.
Thanks @aboutaleb-dev for suggesting this!

**Review by GILLESMaster — APPROVED** [review]
Looks good to me, and this also makes it more clear for future reviews on the code!
Thanks for this awesome contribution!

**Comment by GILLESMaster** [comment]
@aboutaleb-dev is there a way for you to sign your commits?
Thanks in advance!
❤️

**Comment by aboutaleb-dev** [comment]
> @aboutaleb-dev is there a way for you to sign your commits? Thanks in advance! ❤️

You're welcome yes I will do it for next commits!
Is there anything more I can help you with?

**Comment by aboutaleb-dev** [comment]
> > > @aboutaleb-dev is there a way for you to sign your commits? Thanks in advance! ❤️
> > 
> > 
> > You're welcome yes I will do it for next commits! Is there anything more I can help you with?
> 
> Hi thanks again, I can't express enough on how much I appreciate this! I am going to try and make a CRUDs API, (I think thats how its called) So that you can get a API key from the dashboard that is bound to a user account and with that API key you can authenticate requests to the API that handles those requests to a database, and all the MySQL operations are managed, so basically this will be a remote database api wrapper so that all applications or programs can easily integrate a central database with basic HTTP requests, and they dont have to worry about hosting aswell, but if they want to they can run this application locally because it is open source and I plan it to be that way forever because I believe in opensource!
> 
> ❤️

Your welcome, my pleasure can you explain which type of data do you want to do crud on?
I mean fields that user fill to create an object

**Comment by aboutaleb-dev** [comment]
I think by the user id we can find out the data is for authenticated user or not, am I right?

**Comment by aboutaleb-dev** [comment]
> > > > > @aboutaleb-dev is there a way for you to sign your commits? Thanks in advance! ❤️
> > > > 
> > > > 
> > > > You're welcome yes I will do it for next commits! Is there anything more I can help you with?
> > > 
> > > 
> > > Hi thanks again, I can't express enough on how much I appreciate this! I am going to try and make a CRUDs API, (I think thats how its called) So that you can get a API key from the dashboard that is bound to a user account and with that API key you can authenticate requests to the API that handles those requests to a database, and all the MySQL operations are managed, so basically this will be a remote database api wrapper so that all applications or programs can easily integrate a central database with basic HTTP requests, and they dont have to worry about hosting aswell, but if they want to they can run this application locally because it is open source and I plan it to be that way forever because I believe in opensource!
> > > ❤️
> > 
> > 
> > Your welcome, my pleasure can you explain which type of data do you want to do crud on? I mean fields that user fill to create an object
> 
> I would want to make it so that there is a UserID value and the data value that the request wants to access, so a remote game/application can modify that part of the data, I don't know how to make sure that the data they created or want to edit or request is owned by the API key the HTTP request is authenticated with, but other than that it should take 2 parameters for UserID (or profile for the user with that data) and data (the actual data they want to query or want to edit values in, and process those to their MySQL actions).
> 
> But I am relatively new to PHP or Laravel for that matter, so I am still reading all the DOCS and finding out the best solution or way to achieve this.
> 
> And it should go to the DB the Laravel instance is using so the normal Laravel DB expressions could be used.
> 
> If this isn't a clear overview of my goals then let me know! Il try and make it more clear! ❤️ 👍

I think by the user id we can find out the data is for authenticated user or not, am I right?

**Comment by GILLESMaster** [comment]
> > > > > > @aboutaleb-dev is there a way for you to sign your commits? Thanks in advance! ❤️
> > > > > 
> > > > > 
> > > > > You're welcome yes I will do it for next commits! Is there anything more I can help you with?
> > > > 
> > > > 
> > > > Hi thanks again, I can't express enough on how much I appreciate this! I am going to try and make a CRUDs API, (I think thats how its called) So that you can get a API key from the dashboard that is bound to a user account and with that API key you can authenticate requests to the API that handles those requests to a database, and all the MySQL operations are managed, so basically this will be a remote database api wrapper so that all applications or programs can easily integrate a central database with basic HTTP requests, and they dont have to worry about hosting aswell, but if they want to they can run this application locally because it is open source and I plan it to be that way forever because I believe in opensource!
> > > > ❤️
> > > 
> > > 
> > > Your welcome, my pleasure can you explain which type of data do you want to do crud on? I mean fields that user fill to create an object
> > 
> > 
> > I would want to make it so that there is a UserID value and the data value that the request wants to access, so a remote game/application can modify that part of the data, I don't know how to make sure that the data they created or want to edit or request is owned by the API key the HTTP request is authenticated with, but other than that it should take 2 parameters for UserID (or profile for the user with that data) and data (the actual data they want to query or want to edit values in, and process those to their MySQL actions).
> > But I am relatively new to PHP or Laravel for that matter, so I am still reading all the DOCS and finding out the best solution or way to achieve this.
> > And it should go to the DB the Laravel instance is using so the normal Laravel DB expressions could be used.
> > If this isn't a clear overview of my goals then let me know! Il try and make it more clear! ❤️ 👍
> 
> I think by the user id we can find out the data is for authenticated user or not, am I right?

That is not percee what I meant, but yes the userid is something we can figure out, but the authentication should be via a key/API key bound to a registered user, but one of the params for the API is (UserID,) and (Data), because I want to first test this in a roblox envoirment so that I have this a a remote database and wrapper for it so no raw mysql command logic is needed to be made on the roblox server side (for example!) but this can be with any other platfrom without native external database support,
But what I am stuck at is how do I implement the API-KEY and how do I emplement the API itself, the rest is done already, like get vue, vite, all sorts of plugins etc, after that il start on web design and make it so that you can actually see your bound api key, on the dashboard and (in the future) see your data/previous requests (and if I am able to) visualize database usage.

**Comment by aboutaleb-dev** [comment]
> > > > > > > @aboutaleb-dev is there a way for you to sign your commits? Thanks in advance! ❤️
> > > > > > 
> > > > > > 
> > > > > > You're welcome yes I will do it for next commits! Is there anything more I can help you with?
> > > > > 
> > > > > 
> > > > > Hi thanks again, I can't express enough on how much I appreciate this! I am going to try and make a CRUDs API, (I think thats how its called) So that you can get a API key from the dashboard that is bound to a user account and with that API key you can authenticate requests to the API that handles those requests to a database, and all the MySQL operations are managed, so basically this will be a remote database api wrapper so that all applications or programs can easily integrate a central database with basic HTTP requests, and they dont have to worry about hosting aswell, but if they want to they can run this application locally because it is open source and I plan it to be that way forever because I believe in opensource!
> > > > > ❤️
> > > > 
> > > > 
> > > > Your welcome, my pleasure can you explain which type of data do you want to do crud on? I mean fields that user fill to create an object
> > > 
> > > 
> > > I would want to make it so that there is a UserID value and the data value that the request wants to access, so a remote game/application can modify that part of the data, I don't know how to make sure that the data they created or want to edit or request is owned by the API key the HTTP request is authenticated with, but other than that it should take 2 parameters for UserID (or profile for the user with that data) and data (the actual data they want to query or want to edit values in, and process those to their MySQL actions).
> > > But I am relatively new to PHP or Laravel for that matter, so I am still reading all the DOCS and finding out the best solution or way to achieve this.
> > > And it should go to the DB the Laravel instance is using so the normal Laravel DB expressions could be used.
> > > If this isn't a clear overview of my goals then let me know! Il try and make it more clear! ❤️ 👍
> > 
> > 
> > I think by the user id we can find out the data is for authenticated user or not, am I right?
> 
> That is not percee what I meant, but yes the userid is something we can figure out, but the authentication should be via a key/API key bound to a registered user, but one of the params for the API is (UserID,) and (Data), because I want to first test this in a roblox envoirment so that I have this a a remote database and wrapper for it so no raw mysql command logic is needed to be made on the roblox server side (for example!) but this can be with any other platfrom without native external database support, But what I am stuck at is how do I implement the API-KEY and how do I emplement the API itself, the rest is done already, like get vue, vite, all sorts of plugins etc, after that il start on web design and make it so that you can actually see your bound api key, on the dashboard and (in the future) see your data/previous requests (and if I am able to) visualize database usage.

ok fine you can use tokens for that porpuse they are called authorization tokens an are built in in laravel every user log in get one they are in personal_access_tokens tables and can be created with this line of code:

$token = $user->createToken('token')->plainTextToken;

**Comment by GILLESMaster** [comment]
> > > > > > > > @aboutaleb-dev is there a way for you to sign your commits? Thanks in advance! ❤️
> > > > > > > 
> > > > > > > 
> > > > > > > You're welcome yes I will do it for next commits! Is there anything more I can help you with?
> > > > > > 
> > > > > > 
> > > > > > Hi thanks again, I can't express enough on how much I appreciate this! I am going to try and make a CRUDs API, (I think thats how its called) So that you can get a API key from the dashboard that is bound to a user account and with that API key you can authenticate requests to the API that handles those requests to a database, and all the MySQL operations are managed, so basically this will be a remote database api wrapper so that all applications or programs can easily integrate a central database with basic HTTP requests, and they dont have to worry about hosting aswell, but if they want to they can run this application locally because it is open source and I plan it to be that way forever because I believe in opensource!
> > > > > > ❤️
> > > > > 
> > > > > 
> > > > > Your welcome, my pleasure can you explain which type of data do you want to do crud on? I mean fields that user fill to create an object
> > > > 
> > > > 
> > > > I would want to make it so that there is a UserID value and the data value that the request wants to access, so a remote game/application can modify that part of the data, I don't know how to make sure that the data they created or want to edit or request is owned by the API key the HTTP request is authenticated with, but other than that it should take 2 parameters for UserID (or profile for the user with that data) and data (the actual data they want to query or want to edit values in, and process those to their MySQL actions).
> > > > But I am relatively new to PHP or Laravel for that matter, so I am still reading all the DOCS and finding out the best solution or way to achieve this.
> > > > And it should go to the DB the Laravel instance is using so the normal Laravel DB expressions could be used.
> > > > If this isn't a clear overview of my goals then let me know! Il try and make it more clear! ❤️ 👍
> > > 
> > > 
> > > I think by the user id we can find out the data is for authenticated user or not, am I right?
> > 
> > 
> > That is not percee what I meant, but yes the userid is something we can figure out, but the authentication should be via a key/API key bound to a registered user, but one of the params for the API is (UserID,) and (Data), because I want to first test this in a roblox envoirment so that I have this a a remote database and wrapper for it so no raw mysql command logic is needed to be made on the roblox server side (for example!) but this can be with any other platfrom without native external database support, But what I am stuck at is how do I implement the API-KEY and how do I emplement the API itself, the rest is done already, like get vue, vite, all sorts of plugins etc, after that il start on web design and make it so that you can actually see your bound api key, on the dashboard and (in the future) see your data/previous requests (and if I am able to) visualize database usage.
> 
> ok fine you can use tokens for that porpuse they are called authorization tokens an are built in in laravel every user log in get one they are in personal_access_tokens tables and can be created with this line of code:
> 
> $token = $user->createToken('token')->plainTextToken;

Where would I put this?
Inside the model?

I am still learning, but thanks for trying to help me 😄

**Comment by aboutaleb-dev** [comment]
> > > > > > > > > @aboutaleb-dev is there a way for you to sign your commits? Thanks in advance! ❤️
> > > > > > > > 
> > > > > > > > 
> > > > > > > > You're welcome yes I will do it for next commits! Is there anything more I can help you with?
> > > > > > > 
> > > > > > > 
> > > > > > > Hi thanks again, I can't express enough on how much I appreciate this! I am going to try and make a CRUDs API, (I think thats how its called) So that you can get a API key from the dashboard that is bound to a user account and with that API key you can authenticate requests to the API that handles those requests to a database, and all the MySQL operations are managed, so basically this will be a remote database api wrapper so that all applications or programs can easily integrate a central database with basic HTTP requests, and they dont have to worry about hosting aswell, but if they want to they can run this application locally because it is open source and I plan it to be that way forever because I believe in opensource!
> > > > > > > ❤️
> > > > > > 
> > > > > > 
> > > > > > Your welcome, my pleasure can you explain which type of data do you want to do crud on? I mean fields that user fill to create an object
> > > > > 
> > > > > 
> > > > > I would want to make it so that there is a UserID value and the data value that the request wants to access, so a remote game/application can modify that part of the data, I don't know how to make sure that the data they created or want to edit or request is owned by the API key the HTTP request is authenticated with, but other than that it should take 2 parameters for UserID (or profile for the user with that data) and data (the actual data they want to query or want to edit values in, and process those to their MySQL actions).
> > > > > But I am relatively new to PHP or Laravel for that matter, so I am still reading all the DOCS and finding out the best solution or way to achieve this.
> > > > > And it should go to the DB the Laravel instance is using so the normal Laravel DB expressions could be used.
> > > > > If this isn't a clear overview of my goals then let me know! Il try and make it more clear! ❤️ 👍
> > > > 
> > > > 
> > > > I think by the user id we can find out the data is for authenticated user or not, am I right?
> > > 
> > > 
> > > That is not percee what I meant, but yes the userid is something we can figure out, but the authentication should be via a key/API key bound to a registered user, but one of the params for the API is (UserID,) and (Data), because I want to first test this in a roblox envoirment so that I have this a a remote database and wrapper for it so no raw mysql command logic is needed to be made on the roblox server side (for example!) but this can be with any other platfrom without native external database support, But what I am stuck at is how do I implement the API-KEY and how do I emplement the API itself, the rest is done already, like get vue, vite, all sorts of plugins etc, after that il start on web design and make it so that you can actually see your bound api key, on the dashboard and (in the future) see your data/previous requests (and if I am able to) visualize database usage.
> > 
> > 
> > ok fine you can use tokens for that porpuse they are called authorization tokens an are built in in laravel every user log in get one they are in personal_access_tokens tables and can be created with this line of code:
> > $token = $user->createToken('token')->plainTextToken;
> 
> Where would I put this? Inside the model?
> 
> I am still learning, but thanks for trying to help me 😄

Can you provide me the steps that user should do in your app please I'm think I'm not understanding your Idea

**Comment by aboutaleb-dev** [comment]
> service

Now we dont have other service what service should be used and we the api token should be privided by the external server I think

**Comment by aboutaleb-dev** [comment]
> > > > > > > > > > > @aboutaleb-dev is there a way for you to sign your commits? Thanks in advance! ❤️
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > You're welcome yes I will do it for next commits! Is there anything more I can help you with?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Hi thanks again, I can't express enough on how much I appreciate this! I am going to try and make a CRUDs API, (I think thats how its called) So that you can get a API key from the dashboard that is bound to a user account and with that API key you can authenticate requests to the API that handles those requests to a database, and all the MySQL operations are managed, so basically this will be a remote database api wrapper so that all applications or programs can easily integrate a central database with basic HTTP requests, and they dont have to worry about hosting aswell, but if they want to they can run this application locally because it is open source and I plan it to be that way forever because I believe in opensource!
> > > > > > > > > ❤️
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Your welcome, my pleasure can you explain which type of data do you want to do crud on? I mean fields that user fill to create an object
> > > > > > > 
> > > > > > > 
> > > > > > > I would want to make it so that there is a UserID value and the data value that the request wants to access, so a remote game/application can modify that part of the data, I don't know how to make sure that the data they created or want to edit or request is owned by the API key the HTTP request is authenticated with, but other than that it should take 2 parameters for UserID (or profile for the user with that data) and data (the actual data they want to query or want to edit values in, and process those to their MySQL actions).
> > > > > > > But I am relatively new to PHP or Laravel for that matter, so I am still reading all the DOCS and finding out the best solution or way to achieve this.
> > > > > > > And it should go to the DB the Laravel instance is using so the normal Laravel DB expressions could be used.
> > > > > > > If this isn't a clear overview of my goals then let me know! Il try and make it more clear! ❤️ 👍
> > > > > > 
> > > > > > 
> > > > > > I think by the user id we can find out the data is for authenticated user or not, am I right?
> > > > > 
> > > > > 
> > > > > That is not percee what I meant, but yes the userid is something we can figure out, but the authentication should be via a key/API key bound to a registered user, but one of the params for the API is (UserID,) and (Data), because I want to first test this in a roblox envoirment so that I have this a a remote database and wrapper for it so no raw mysql command logic is needed to be made on the roblox server side (for example!) but this can be with any other platfrom without native external database support, But what I am stuck at is how do I implement the API-KEY and how do I emplement the API itself, the rest is done already, like get vue, vite, all sorts of plugins etc, after that il start on web design and make it so that you can actually see your bound api key, on the dashboard and (in the future) see your data/previous requests (and if I am able to) visualize database usage.
> > > > 
> > > > 
> > > > ok fine you can use tokens for that porpuse they are called authorization tokens an are built in in laravel every user log in get one they are in personal_access_tokens tables and can be created with this line of code:
> > > > $token = $user->createToken('token')->plainTextToken;
> > > 
> > > 
> > > Where would I put this? Inside the model?
> > > I am still learning, but thanks for trying to help me 😄
> > 
> > 
> > Can you provide me the steps that user should do in your app please I'm think I'm not understanding your Idea
> 
> So, a user registers on the site, gets to see his API token and with that token the user can authenticate http json requests (so from a other server/service) and get Database actions permissions to only on a specific part of the database that has been asigned to the token aswell

Now we dont have other service what service should be used and we the api token should be privided by the external server I think

**Comment by GILLESMaster** [comment]
> > > > > > > > > > > > @aboutaleb-dev is there a way for you to sign your commits? Thanks in advance! ❤️
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > You're welcome yes I will do it for next commits! Is there anything more I can help you with?
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Hi thanks again, I can't express enough on how much I appreciate this! I am going to try and make a CRUDs API, (I think thats how its called) So that you can get a API key from the dashboard that is bound to a user account and with that API key you can authenticate requests to the API that handles those requests to a database, and all the MySQL operations are managed, so basically this will be a remote database api wrapper so that all applications or programs can easily integrate a central database with basic HTTP requests, and they dont have to worry about hosting aswell, but if they want to they can run this application locally because it is open source and I plan it to be that way forever because I believe in opensource!
> > > > > > > > > > ❤️
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Your welcome, my pleasure can you explain which type of data do you want to do crud on? I mean fields that user fill to create an object
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I would want to make it so that there is a UserID value and the data value that the request wants to access, so a remote game/application can modify that part of the data, I don't know how to make sure that the data they created or want to edit or request is owned by the API key the HTTP request is authenticated with, but other than that it should take 2 parameters for UserID (or profile for the user with that data) and data (the actual data they want to query or want to edit values in, and process those to their MySQL actions).
> > > > > > > > But I am relatively new to PHP or Laravel for that matter, so I am still reading all the DOCS and finding out the best solution or way to achieve this.
> > > > > > > > And it should go to the DB the Laravel instance is using so the normal Laravel DB expressions could be used.
> > > > > > > > If this isn't a clear overview of my goals then let me know! Il try and make it more clear! ❤️ 👍
> > > > > > > 
> > > > > > > 
> > > > > > > I think by the user id we can find out the data is for authenticated user or not, am I right?
> > > > > > 
> > > > > > 
> > > > > > That is not percee what I meant, but yes the userid is something we can figure out, but the authentication should be via a key/API key bound to a registered user, but one of the params for the API is (UserID,) and (Data), because I want to first test this in a roblox envoirment so that I have this a a remote database and wrapper for it so no raw mysql command logic is needed to be made on the roblox server side (for example!) but this can be with any other platfrom without native external database support, But what I am stuck at is how do I implement the API-KEY and how do I emplement the API itself, the rest is done already, like get vue, vite, all sorts of plugins etc, after that il start on web design and make it so that you can actually see your bound api key, on the dashboard and (in the future) see your data/previous requests (and if I am able to) visualize database usage.
> > > > > 
> > > > > 
> > > > > ok fine you can use tokens for that porpuse they are called authorization tokens an are built in in laravel every user log in get one they are in personal_access_tokens tables and can be created with this line of code:
> > > > > $token = $user->createToken('token')->plainTextToken;
> > > > 
> > > > 
> > > > Where would I put this? Inside the model?
> > > > I am still learning, but thanks for trying to help me 😄
> > > 
> > > 
> > > Can you provide me the steps that user should do in your app please I'm think I'm not understanding your Idea
> > 
> > 
> > So, a user registers on the site, gets to see his API token and with that token the user can authenticate HTTP JSON requests (so from a other server/service) and get Database actions permissions to only on a specific part of the database that has been assigned to the token as well
> 
> Now we don't have other service what service should be used and we the api token should be provided by the external server I think

I have implemented the api_token 🥳 
But about the api logic, I am also unsure, but we would need like 2 inputs (input one will be scope (so that it can be used to identify data for that scope) and input one will be data (a table that actually represents the data corresponding to the scope))

**Comment by aboutaleb-dev** [comment]
> > > > > > > > > > > > > @aboutaleb-dev is there a way for you to sign your commits? Thanks in advance! ❤️
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > You're welcome yes I will do it for next commits! Is there anything more I can help you with?
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > Hi thanks again, I can't express enough on how much I appreciate this! I am going to try and make a CRUDs API, (I think thats how its called) So that you can get a API key from the dashboard that is bound to a user account and with that API key you can authenticate requests to the API that handles those requests to a database, and all the MySQL operations are managed, so basically this will be a remote database api wrapper so that all applications or programs can easily integrate a central database with basic HTTP requests, and they dont have to worry about hosting aswell, but if they want to they can run this application locally because it is open source and I plan it to be that way forever because I believe in opensource!
> > > > > > > > > > > ❤️
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Your welcome, my pleasure can you explain which type of data do you want to do crud on? I mean fields that user fill to create an object
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > I would want to make it so that there is a UserID value and the data value that the request wants to access, so a remote game/application can modify that part of the data, I don't know how to make sure that the data they created or want to edit or request is owned by the API key the HTTP request is authenticated with, but other than that it should take 2 parameters for UserID (or profile for the user with that data) and data (the actual data they want to query or want to edit values in, and process those to their MySQL actions).
> > > > > > > > > But I am relatively new to PHP or Laravel for that matter, so I am still reading all the DOCS and finding out the best solution or way to achieve this.
> > > > > > > > > And it should go to the DB the Laravel instance is using so the normal Laravel DB expressions could be used.
> > > > > > > > > If this isn't a clear overview of my goals then let me know! Il try and make it more clear! ❤️ 👍
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I think by the user id we can find out the data is for authenticated user or not, am I right?
> > > > > > > 
> > > > > > > 
> > > > > > > That is not percee what I meant, but yes the userid is something we can figure out, but the authentication should be via a key/API key bound to a registered user, but one of the params for the API is (UserID,) and (Data), because I want to first test this in a roblox envoirment so that I have this a a remote database and wrapper for it so no raw mysql command logic is needed to be made on the roblox server side (for example!) but this can be with any other platfrom without native external database support, But what I am stuck at is how do I implement the API-KEY and how do I emplement the API itself, the rest is done already, like get vue, vite, all sorts of plugins etc, after that il start on web design and make it so that you can actually see your bound api key, on the dashboard and (in the future) see your data/previous requests (and if I am able to) visualize database usage.
> > > > > > 
> > > > > > 
> > > > > > ok fine you can use tokens for that porpuse they are called authorization tokens an are built in in laravel every user log in get one they are in personal_access_tokens tables and can be created with this line of code:
> > > > > > $token = $user->createToken('token')->plainTextToken;
> > > > > 
> > > > > 
> > > > > Where would I put this? Inside the model?
> > > > > I am still learning, but thanks for trying to help me 😄
> > > > 
> > > > 
> > > > Can you provide me the steps that user should do in your app please I'm think I'm not understanding your Idea
> > > 
> > > 
> > > So, a user registers on the site, gets to see his API token and with that token the user can authenticate HTTP JSON requests (so from a other server/service) and get Database actions permissions to only on a specific part of the database that has been assigned to the token as well
> > 
> > 
> > Now we don't have other service what service should be used and we the api token should be provided by the external server I think
> 
> I have implemented the api_token 🥳 But about the api logic, I am also unsure, but we would need like 2 inputs (input one will be scope (so that it can be used to identify data for that scope) and input one will be data (a table that actually represents the data corresponding to the scope))

very good nice 
how can I get my api token? I currently get No API token available message

**Comment by GILLESMaster** [comment]
> > > > > > > > > > > > > > @aboutaleb-dev is there a way for you to sign your commits? Thanks in advance! ❤️
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > You're welcome yes I will do it for next commits! Is there anything more I can help you with?
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > Hi thanks again, I can't express enough on how much I appreciate this! I am going to try and make a CRUDs API, (I think thats how its called) So that you can get a API key from the dashboard that is bound to a user account and with that API key you can authenticate requests to the API that handles those requests to a database, and all the MySQL operations are managed, so basically this will be a remote database api wrapper so that all applications or programs can easily integrate a central database with basic HTTP requests, and they dont have to worry about hosting aswell, but if they want to they can run this application locally because it is open source and I plan it to be that way forever because I believe in opensource!
> > > > > > > > > > > > ❤️
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > Your welcome, my pleasure can you explain which type of data do you want to do crud on? I mean fields that user fill to create an object
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > I would want to make it so that there is a UserID value and the data value that the request wants to access, so a remote game/application can modify that part of the data, I don't know how to make sure that the data they created or want to edit or request is owned by the API key the HTTP request is authenticated with, but other than that it should take 2 parameters for UserID (or profile for the user with that data) and data (the actual data they want to query or want to edit values in, and process those to their MySQL actions).
> > > > > > > > > > But I am relatively new to PHP or Laravel for that matter, so I am still reading all the DOCS and finding out the best solution or way to achieve this.
> > > > > > > > > > And it should go to the DB the Laravel instance is using so the normal Laravel DB expressions could be used.
> > > > > > > > > > If this isn't a clear overview of my goals then let me know! Il try and make it more clear! ❤️ 👍
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > I think by the user id we can find out the data is for authenticated user or not, am I right?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > That is not percee what I meant, but yes the userid is something we can figure out, but the authentication should be via a key/API key bound to a registered user, but one of the params for the API is (UserID,) and (Data), because I want to first test this in a roblox envoirment so that I have this a a remote database and wrapper for it so no raw mysql command logic is needed to be made on the roblox server side (for example!) but this can be with any other platfrom without native external database support, But what I am stuck at is how do I implement the API-KEY and how do I emplement the API itself, the rest is done already, like get vue, vite, all sorts of plugins etc, after that il start on web design and make it so that you can actually see your bound api key, on the dashboard and (in the future) see your data/previous requests (and if I am able to) visualize database usage.
> > > > > > > 
> > > > > > > 
> > > > > > > ok fine you can use tokens for that porpuse they are called authorization tokens an are built in in laravel every user log in get one they are in personal_access_tokens tables and can be created with this line of code:
> > > > > > > $token = $user->createToken('token')->plainTextToken;
> > > > > > 
> > > > > > 
> > > > > > Where would I put this? Inside the model?
> > > > > > I am still learning, but thanks for trying to help me 😄
> > > > > 
> > > > > 
> > > > > Can you provide me the steps that user should do in your app please I'm think I'm not understanding your Idea
> > > > 
> > > > 
> > > > So, a user registers on the site, gets to see his API token and with that token the user can authenticate HTTP JSON requests (so from a other server/service) and get Database actions permissions to only on a specific part of the database that has been assigned to the token as well
> > > 
> > > 
> > > Now we don't have other service what service should be used and we the api token should be provided by the external server I think
> > 
> > 
> > I have implemented the api_token 🥳 But about the api logic, I am also unsure, but we would need like 2 inputs (input one will be scope (so that it can be used to identify data for that scope) and input one will be data (a table that actually represents the data corresponding to the scope))
> 
> very good nice how can I get my api token? I currently get No API token available message

You have to clear the database and reregister your account!
The logic in the session control and the register control have been reworked!!

**Comment by aboutaleb-dev** [comment]
> > > > > > > > > > > > > > > @aboutaleb-dev is there a way for you to sign your commits? Thanks in advance! ❤️
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > You're welcome yes I will do it for next commits! Is there anything more I can help you with?
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > Hi thanks again, I can't express enough on how much I appreciate this! I am going to try and make a CRUDs API, (I think thats how its called) So that you can get a API key from the dashboard that is bound to a user account and with that API key you can authenticate requests to the API that handles those requests to a database, and all the MySQL operations are managed, so basically this will be a remote database api wrapper so that all applications or programs can easily integrate a central database with basic HTTP requests, and they dont have to worry about hosting aswell, but if they want to they can run this application locally because it is open source and I plan it to be that way forever because I believe in opensource!
> > > > > > > > > > > > > ❤️
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > Your welcome, my pleasure can you explain which type of data do you want to do crud on? I mean fields that user fill to create an object
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > I would want to make it so that there is a UserID value and the data value that the request wants to access, so a remote game/application can modify that part of the data, I don't know how to make sure that the data they created or want to edit or request is owned by the API key the HTTP request is authenticated with, but other than that it should take 2 parameters for UserID (or profile for the user with that data) and data (the actual data they want to query or want to edit values in, and process those to their MySQL actions).
> > > > > > > > > > > But I am relatively new to PHP or Laravel for that matter, so I am still reading all the DOCS and finding out the best solution or way to achieve this.
> > > > > > > > > > > And it should go to the DB the Laravel instance is using so the normal Laravel DB expressions could be used.
> > > > > > > > > > > If this isn't a clear overview of my goals then let me know! Il try and make it more clear! ❤️ 👍
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > I think by the user id we can find out the data is for authenticated user or not, am I right?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > That is not percee what I meant, but yes the userid is something we can figure out, but the authentication should be via a key/API key bound to a registered user, but one of the params for the API is (UserID,) and (Data), because I want to first test this in a roblox envoirment so that I have this a a remote database and wrapper for it so no raw mysql command logic is needed to be made on the roblox server side (for example!) but this can be with any other platfrom without native external database support, But what I am stuck at is how do I implement the API-KEY and how do I emplement the API itself, the rest is done already, like get vue, vite, all sorts of plugins etc, after that il start on web design and make it so that you can actually see your bound api key, on the dashboard and (in the future) see your data/previous requests (and if I am able to) visualize database usage.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ok fine you can use tokens for that porpuse they are called authorization tokens an are built in in laravel every user log in get one they are in personal_access_tokens tables and can be created with this line of code:
> > > > > > > > $token = $user->createToken('token')->plainTextToken;
> > > > > > > 
> > > > > > > 
> > > > > > > Where would I put this? Inside the model?
> > > > > > > I am still learning, but thanks for trying to help me 😄
> > > > > > 
> > > > > > 
> > > > > > Can you provide me the steps that user should do in your app please I'm think I'm not understanding your Idea
> > > > > 
> > > > > 
> > > > > So, a user registers on the site, gets to see his API token and with that token the user can authenticate HTTP JSON requests (so from a other server/service) and get Database actions permissions to only on a specific part of the database that has been assigned to the token as well
> > > > 
> > > > 
> > > > Now we don't have other service what service should be used and we the api token should be provided by the external server I think
> > > 
> > > 
> > > I have implemented the api_token 🥳 But about the api logic, I am also unsure, but we would need like 2 inputs (input one will be scope (so that it can be used to identify data for that scope) and input one will be data (a table that actually represents the data corresponding to the scope))
> > 
> > 
> > very good nice how can I get my api token? I currently get No API token available message
> 
> You have to clear the database and reregister your account! The logic in the session control and the register control have been reworked!!

yes nice I got it very good!

**Pull request merged**
