### PR TITLE
resorting migrations

### PR DESCRIPTION
**Pull request by aboutaleb-dev**
I have added api_token column to user migration and deleted 2023_05_26_173837_add_api_token_to_users_table.php I think this way the app is more robust but at the end it is your decision

### CODE REVIEW

**Comment by GILLESMaster** [comment]
yup lol forgot to do that, because it was for testing lol, didnt think of updating it!
@aboutaleb-dev thanks again!

**Comment by GILLESMaster** [comment]
@aboutaleb-dev why is there the ->nullable()?
What does it provide/do extra?
I suppose make it possible to be null?

**Comment by aboutaleb-dev** [comment]
yes it will make it possible for its value to be null

**Comment by GILLESMaster** [comment]
@aboutaleb-dev 
ChatGPT (might be inaccurate!!!!!)

"The `nullable()` method in Laravel's migration schema builder specifies that a column allows `NULL` values. Here's the difference between using `$table->text('api_token')->nullable();` and `$table->text('api_token');`:

1. `$table->text('api_token')->nullable();`: This statement creates a column named `api_token` with the `text` data type, and it allows `NULL` values. This means that the `api_token` column can either store a valid token or be empty (`NULL`).

2. `$table->text('api_token');`: This statement creates a column named `api_token` with the `text` data type. However, it does not specify the `nullable()` method. In this case, the `api_token` column will not allow `NULL` values, and a value must be provided for the column when inserting or updating rows.

By adding `nullable()` to the column definition, you make it possible to have `NULL` values in the `api_token` column. This can be useful in scenarios where a user may not have an API token assigned yet or when the token is optional.

The choice of whether to include `nullable()` depends on your application's requirements. If having a nullable `api_token` is acceptable and aligns with your logic, you can include `nullable()`. Otherwise, if every user is expected to have an API token, you can omit `nullable()` to enforce the presence of a token value."


Is that correct?
If so does it matter that much?

**Comment by GILLESMaster** [comment]
> yes it will make it possible for its value to be null

ah I see

> @aboutaleb-dev ChatGPT (might be inaccurate!!!!!)
> 
> "The `nullable()` method in Laravel's migration schema builder specifies that a column allows `NULL` values. Here's the difference between using `$table->text('api_token')->nullable();` and `$table->text('api_token');`:
> 
>     1. `$table->text('api_token')->nullable();`: This statement creates a column named `api_token` with the `text` data type, and it allows `NULL` values. This means that the `api_token` column can either store a valid token or be empty (`NULL`).
> 
>     2. `$table->text('api_token');`: This statement creates a column named `api_token` with the `text` data type. However, it does not specify the `nullable()` method. In this case, the `api_token` column will not allow `NULL` values, and a value must be provided for the column when inserting or updating rows.
> 
> 
> By adding `nullable()` to the column definition, you make it possible to have `NULL` values in the `api_token` column. This can be useful in scenarios where a user may not have an API token assigned yet or when the token is optional.
> 
> The choice of whether to include `nullable()` depends on your application's requirements. If having a nullable `api_token` is acceptable and aligns with your logic, you can include `nullable()`. Otherwise, if every user is expected to have an API token, you can omit `nullable()` to enforce the presence of a token value."
> 
> Is that correct? If so does it matter that much?

But then again, should we include it or not?
Because after all, every user would have a ID, or maybe it would be better to accept nil values if a new one is generated (yet to implement remake of key)

**Review by GILLESMaster — APPROVED** [review]
Nice update, confused at first but looks good to me!
Now I can try and make the api_token be able to regenerate if the user requests that

**Comment by aboutaleb-dev** [comment]
> 

yes it is correct it depends on what you want your application to be if you want databse to accept null values when inserting user you can keep the nullable() but if you want to only save user that has api token you should discard nullable()
in the case when you insert user to database without api_token you will get an error and you app is strict about that

**Comment by GILLESMaster** [comment]
> > 
> 
> yes it is correct it depends on what you want your application to be if you want databse to accept null values when inserting user you can keep the nullable() but if you want to only save user that has api token you should discard nullable() in the case when you insert user to database without api_token you will get an error and you app is strict about that

I think il accept the ->Nullable()
You learn something new everyday! 😉

**Pull request merged**
